export const CHANGE_CONTENT_DATA = 'detail/CHANGE_CONTENT_DATA';
export const CHANGE_OTHER_CONTENT = 'detail/CHANGE_OTHER_CONTENT';
export const CHANGE_RECOMMEND_CONTENT = 'detail/CHANGE_RECOMMEND_CONTENT';
export const CHANGE_CONTENT_SPIN = 'detail/CHANGE_CONTENT_SPIN';

